# Generated by Django 5.0.3 on 2024-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARRIER', '0002_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='listof_College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=10)),
                ('cutoff', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
